# Generated by Django 6.0.4 on 2026-06-22 09:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_issue_creation_status_issue_intelligence_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_token', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_reports', to='core.project')),
            ],
            options={
                'db_table': 'core_client_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='submissions/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.project')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_team_submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
